export {
  mockFinancialStatus,
  mockIncomes,
  mockAssets,
  mockLiabilities,
  mockChildExpense,
  mockStartDialog,
  mockRepayDialog,
  mockDownsizedDialog,
  mockBabyDialogNew,
  mockBabyDialogLimitReached,
  mockOpportunityDialog,
  mockSmallDeal,
  mockBigDeal,
  mockMarket,
} from './mockProps'
